// Command genembed turns a gateway config file into a Go source file holding the
// config as base64 string chunks, so the compiled binary carries it and the
// plaintext never reaches a filesystem the image ships.
//
//	go run ./cmd/genembed <config-file> <out.go>
//
// It is run by the Dockerfile with the config arriving as a BuildKit secret.
package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: genembed <config-file> <out.go>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "read:", err)
		os.Exit(1)
	}
	enc := base64.StdEncoding.EncodeToString(raw)
	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString("// Code generated by cmd/genembed at image build time. DO NOT EDIT.\n")
	b.WriteString("// Source: BuildKit secret (plaintext never enters a layer).\n\n")
	b.WriteString("func embeddedChunks() []string {\n\treturn []string{\n")
	for i := 0; i < len(enc); i += 2 {
		end := i + 2
		if end > len(enc) {
			end = len(enc)
		}
		fmt.Fprintf(&b, "\t\t%q,\n", enc[i:end])
	}
	b.WriteString("\t}\n}\n")
	if err := os.WriteFile(os.Args[2], []byte(b.String()), 0o600); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
}
